package com.pq.ideas.enums;

public enum TokenDetailsKeys {
	TIMEOUT_IN_MINUTES, 
	TOKEN_EXPIRED, 
	LOCAL_USER,
	TOKEN, 
	HEADER, 
	HEADER_VALUES, 
	HEADER_USER_ROLES,
	TOKEN_INEXISTENT,
	CACHE_MAX_NUMBER_OF_TRY,
	MINIMUM_PASSWORD_SIZE;
}
